### ISSUE TITLE
Lint tools + testing tools should be in dev dependencies

### ISSUE THREAD

**Issue by RusseII** [sparksuite/salary-calculator#71]
I see they got removed in https://github.com/sparksuite/salary-calculator/commit/b636a0ffd851cba0aba09279afe4cbea3d7ecb5b - why? 

https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies 

	
Example of some packages that should be in dev dependencies: 
		"@storybook/react": "^6.1.1",
		"@testing-library/jest-dom": "^5.11.6",
		"@testing-library/react": "^11.2.1",
		"@testing-library/user-event": "^12.2.2",
		"@types/jest": "^26.0.15",
		"@types/node": "^14.14.9",
		"@types/react": "^17.0.0",
		"@types/react-dom": "^17.0.0",
		"@types/react-redux": "^7.1.2",
		"@types/styled-components": "^5.1.4",
		"@typescript-eslint/eslint-plugin": "^4.8.1",
		"@typescript-eslint/parser": "^4.8.1",
		"babel-eslint": "^10.0.3",
		"babel-loader": "8.1.0",
		"babel-plugin-macros": "^2.6.1",
		"eslint": "^7.13.0",
		"eslint-config-prettier": "^6.3.0",
		"eslint-config-react-app": "^6.0.0",
		"eslint-plugin-flowtype": "^5.2.0",
		"eslint-plugin-import": "^2.18.2",
		"eslint-plugin-jsx-a11y": "^6.2.3",
		"eslint-plugin-react": "^7.14.3",
		"eslint-plugin-react-hooks": "^4.2.0",
		"prettier": "^2.2.0",

**Comment by WesCossick** [comment]
Since this project gets compiled and built into static JavaScript, HTML, and CSS files, which are the only assets that get published to Cloudflare Worker Sites, there's no benefit in distinguishing between `dependencies` and `devDependencies`. Doing so only adds mental overhead when managing dependencies.
